/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as TomatoCoinContractJson } from "../TomatoCoin.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace TomatoCoinTypes {
  export type Fields = {};

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<TomatoCoinInstance, {}> {
  encodeFields(fields: TomatoCoinTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  at(address: string): TomatoCoinInstance {
    return new TomatoCoinInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<TomatoCoinTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<TomatoCoinTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<TomatoCoinTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<TomatoCoinTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TomatoCoin = new Factory(
  Contract.fromJson(
    TomatoCoinContractJson,
    "",
    "287b6672c462e1565543750210353d9115aadd8d46608356fbc3f99307610d75",
    []
  )
);

// Use this class to interact with the blockchain
export class TomatoCoinInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TomatoCoinTypes.State> {
    return fetchContractState(TomatoCoin, this);
  }

  view = {
    getSymbol: async (
      params?: TomatoCoinTypes.CallMethodParams<"getSymbol">
    ): Promise<TomatoCoinTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        TomatoCoin,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: TomatoCoinTypes.CallMethodParams<"getName">
    ): Promise<TomatoCoinTypes.CallMethodResult<"getName">> => {
      return callMethod(
        TomatoCoin,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: TomatoCoinTypes.CallMethodParams<"getDecimals">
    ): Promise<TomatoCoinTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        TomatoCoin,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: TomatoCoinTypes.CallMethodParams<"getTotalSupply">
    ): Promise<TomatoCoinTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        TomatoCoin,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: TomatoCoinTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<TomatoCoinTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(TomatoCoin, this, "getSymbol", params);
    },
    getName: async (
      params: TomatoCoinTypes.SignExecuteMethodParams<"getName">
    ): Promise<TomatoCoinTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(TomatoCoin, this, "getName", params);
    },
    getDecimals: async (
      params: TomatoCoinTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<TomatoCoinTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(TomatoCoin, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: TomatoCoinTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<TomatoCoinTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(TomatoCoin, this, "getTotalSupply", params);
    },
  };

  async multicall<Callss extends TomatoCoinTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<TomatoCoinTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      TomatoCoin,
      this,
      callss,
      getContractByCodeHash
    )) as TomatoCoinTypes.MulticallReturnType<Callss>;
  }
}
